// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASbeVb_QEiHK3H4PM1LbGeqTPolQ_N_QM',
    appId: '1:1067458593795:web:b67fc459c72f1bb8123a36',
    messagingSenderId: '1067458593795',
    projectId: 'dwlr-project-95a3b',
    authDomain: 'dwlr-project-95a3b.firebaseapp.com',
    storageBucket: 'dwlr-project-95a3b.firebasestorage.app',
    measurementId: 'G-ZYVH54G129',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTUTE_a2YYaZVzjbKsJFfSYDTyF6bBVkQ',
    appId: '1:1067458593795:android:01531b03f7acfc65123a36',
    messagingSenderId: '1067458593795',
    projectId: 'dwlr-project-95a3b',
    storageBucket: 'dwlr-project-95a3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjm4LdTfbf0cTdzSXjozjS-hxBPT0oHW0',
    appId: '1:1067458593795:ios:159d58cd029a0c7c123a36',
    messagingSenderId: '1067458593795',
    projectId: 'dwlr-project-95a3b',
    storageBucket: 'dwlr-project-95a3b.firebasestorage.app',
    iosBundleId: 'com.example.dwrlProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjm4LdTfbf0cTdzSXjozjS-hxBPT0oHW0',
    appId: '1:1067458593795:ios:159d58cd029a0c7c123a36',
    messagingSenderId: '1067458593795',
    projectId: 'dwlr-project-95a3b',
    storageBucket: 'dwlr-project-95a3b.firebasestorage.app',
    iosBundleId: 'com.example.dwrlProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASbeVb_QEiHK3H4PM1LbGeqTPolQ_N_QM',
    appId: '1:1067458593795:web:f5b185146da845dd123a36',
    messagingSenderId: '1067458593795',
    projectId: 'dwlr-project-95a3b',
    authDomain: 'dwlr-project-95a3b.firebaseapp.com',
    storageBucket: 'dwlr-project-95a3b.firebasestorage.app',
    measurementId: 'G-TYCT76CBKB',
  );
}
